POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}
###
POST http://localhost:3000/login/
Content-Type: application/json

{
  "username":"JoeBiden",
  "password":"biden@123"
}

###
GET http://localhost:3000/user/tweets/feed/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjg0NDc4OTEwfQ.k7VFgO6NoJMblwjBLywIf374Y5CXa5tIG_9KeL1GViQ

###
GET http://localhost:3000/user/following/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjg0NDc4OTEwfQ.k7VFgO6NoJMblwjBLywIf374Y5CXa5tIG_9KeL1GViQ

###

GET http://localhost:3000/user/followers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjg0NDc4OTEwfQ.k7VFgO6NoJMblwjBLywIf374Y5CXa5tIG_9KeL1GViQ
###
GET http://localhost:3000/tweets/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjg0NDc4OTEwfQ.k7VFgO6NoJMblwjBLywIf374Y5CXa5tIG_9KeL1GViQ
###
GET http://localhost:3000/tweets/1/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjg0NDc4OTEwfQ.k7VFgO6NoJMblwjBLywIf374Y5CXa5tIG_9KeL1GViQ

###
GET http://localhost:3000/tweets/1/replies/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjg0NDc4OTEwfQ.k7VFgO6NoJMblwjBLywIf374Y5CXa5tIG_9KeL1GViQ
###
GET http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjg0NDc4OTEwfQ.k7VFgO6NoJMblwjBLywIf374Y5CXa5tIG_9KeL1GViQ
Content-Type: application/json
{
  "username":"JoeBiden",
  "password":"biden@123"
}
###
POST http://localhost:3000/user/tweets/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjg0NDc4OTEwfQ.k7VFgO6NoJMblwjBLywIf374Y5CXa5tIG_9KeL1GViQ

###
DELETE http://localhost:3000/tweets/:tweetId
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvZUJpZGVuIiwiaWF0IjoxNjg0NDc4OTEwfQ.k7VFgO6NoJMblwjBLywIf374Y5CXa5tIG_9KeL1GViQ
###
